---
name: LCIO interface

on:
  push:
    branches: [main]
  pull_request:

env:
  BUILD_TYPE: Release

jobs:
  Root:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2.0
      with:
        cmake-version: 3.23.x
        github-api-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@v5

    - name: 🔧 Configure
      run: cmake -G Ninja -S . -B ./build -DCMAKE_BUILD_TYPE=Release -DBUILD_ROOT_INTERFACE=OFF -DBUILD_LCIO_INTERFACE=ON -DBUILD_RAWDATA_INTERFACE=OFF

    - name: ⚙️ Build
      run: cmake --build ./build --config Release --parallel 2

    - name: Install
      run: cmake --install build

    - name: Test
      run: ctest -C Debug -VV
      working-directory: ./build
