name: "Linux GCC"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  CXX: g++-9
  CC: gcc-9
  
jobs:
  job:
    name: "Linux GCC"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
        
      - name: Configure
        run: mkdir build && cd build && cmake -DBUILD_ROOT_INTERFACE=OFF -DCMAKE_INSTALL_PREFIX=../bin ..
      - name: Build
        run: cmake --build build
      - name: Install
        run: cmake --install build
      - name: Deploy doc
        uses: peaceiris/actions-gh-pages@v2.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          force_orphan: true
          PUBLISH_DIR: ./bin/docs/html
