---
name: Linux Clang

on:
  push:
    branches: [main]
  pull_request:

env:
  BUILD_TYPE: Release
  CXX: clang++
  CC: clang

jobs:
  job:
    name: Linux Clang
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Configure
      run: mkdir build && cd build && cmake -DBUILD_ROOT_INTERFACE=OFF -DCMAKE_INSTALL_PREFIX=../bin ..
    - name: Build
      run: cmake --build build
    - name: Install
      run: cmake --install build
